name: base
channels:
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_kmp_llvm
  - alembic=1.8.1=pyhd8ed1ab_0
  - altair=4.2.0=pyhd8ed1ab_1
  - anyio=3.6.1=pyhd8ed1ab_1
  - aom=3.4.0=h27087fc_1
  - argon2-cffi=21.3.0=pyhd8ed1ab_0
  - argon2-cffi-bindings=21.2.0=py310h5764c6d_2
  - asttokens=2.0.8=pyhd8ed1ab_0
  - async_generator=1.10=py_0
  - attrs=22.1.0=pyh71513ae_1
  - babel=2.10.3=pyhd8ed1ab_0
  - backcall=0.2.0=pyh9f0ad1d_0
  - backports=1.0=py_2
  - backports.functools_lru_cache=1.6.4=pyhd8ed1ab_0
  - beautifulsoup4=4.11.1=pyha770c72_0
  - blas=2.116=openblas
  - blas-devel=3.9.0=16_linux64_openblas
  - bleach=5.0.1=pyhd8ed1ab_0
  - blinker=1.4=py_1
  - blosc=1.21.1=h83bc5f7_3
  - bokeh=2.4.3=pyhd8ed1ab_3
  - bottleneck=1.3.5=py310hde88566_0
  - brotli=1.0.9=h166bdaf_7
  - brotli-bin=1.0.9=h166bdaf_7
  - brotlipy=0.7.0=py310h5764c6d_1004
  - brunsli=0.1=h9c3ff4c_0
  - bzip2=1.0.8=h7f98852_4
  - c-ares=1.18.1=h7f98852_0
  - c-blosc2=2.3.1=h7a311fb_0
  - ca-certificates=2022.6.15=ha878542_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - certifi=2022.6.15=pyhd8ed1ab_1
  - certipy=0.1.3=py_0
  - cffi=1.15.1=py310h255011f_0
  - cfitsio=4.1.0=hd9d235c_0
  - charls=2.3.4=h9c3ff4c_0
  - charset-normalizer=2.1.1=pyhd8ed1ab_0
  - click=8.1.3=py310hff52083_0
  - cloudpickle=2.1.0=pyhd8ed1ab_0
  - colorama=0.4.5=pyhd8ed1ab_0
  - conda=4.14.0=py310hff52083_0
  - conda-package-handling=1.8.1=py310h5764c6d_1
  - configurable-http-proxy=4.5.1=node17_h7e777a6_1
  - cryptography=37.0.4=py310h597c629_0
  - cycler=0.11.0=pyhd8ed1ab_0
  - cython=0.29.32=py310hd8f1fbe_0
  - cytoolz=0.12.0=py310h5764c6d_0
  - dask=2022.8.1=pyhd8ed1ab_2
  - dask-core=2022.8.1=pyhd8ed1ab_0
  - dav1d=1.0.0=h166bdaf_1
  - debugpy=1.6.3=py310hd8f1fbe_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - dill=0.3.5.1=pyhd8ed1ab_0
  - distributed=2022.8.1=pyhd8ed1ab_2
  - entrypoints=0.4=pyhd8ed1ab_0
  - executing=0.10.0=pyhd8ed1ab_0
  - flit-core=3.7.1=pyhd8ed1ab_0
  - fonttools=4.37.1=py310h5764c6d_0
  - freetype=2.12.1=hca18f0e_0
  - fsspec=2022.7.1=pyhd8ed1ab_0
  - giflib=5.2.1=h36c2ea0_2
  - gmp=6.2.1=h58526e2_0
  - gmpy2=2.1.2=py310h92f7908_0
  - greenlet=1.1.3=py310hd8f1fbe_0
  - h5py=3.7.0=nompi_py310h416281c_101
  - hdf5=1.12.2=nompi_h2386368_100
  - heapdict=1.0.1=py_0
  - icu=70.1=h27087fc_0
  - idna=3.3=pyhd8ed1ab_0
  - imagecodecs=2022.8.8=py310h61cb99f_4
  - imageio=2.21.1=pyhfa7a67d_0
  - importlib-metadata=4.11.4=py310hff52083_0
  - importlib_metadata=4.11.4=hd8ed1ab_0
  - importlib_resources=5.9.0=pyhd8ed1ab_0
  - ipykernel=6.15.1=pyh210e3f2_0
  - ipympl=0.9.2=pyhd8ed1ab_0
  - ipython=8.4.0=pyh41d4057_1
  - ipython_genutils=0.2.0=py_1
  - ipywidgets=8.0.1=pyhd8ed1ab_0
  - jedi=0.18.1=pyhd8ed1ab_2
  - jinja2=3.1.2=pyhd8ed1ab_1
  - joblib=1.1.0=pyhd8ed1ab_0
  - jpeg=9e=h166bdaf_2
  - json5=0.9.5=pyh9f0ad1d_0
  - jsonschema=4.14.0=pyhd8ed1ab_0
  - jupyter_client=7.3.4=pyhd8ed1ab_0
  - jupyter_core=4.11.1=py310hff52083_0
  - jupyter_server=1.18.1=pyhd8ed1ab_0
  - jupyter_telemetry=0.1.0=pyhd8ed1ab_1
  - jupyterhub=2.3.1=pyhd8ed1ab_0
  - jupyterhub-base=2.3.1=pyhd8ed1ab_0
  - jupyterlab=3.4.5=pyhd8ed1ab_0
  - jupyterlab_pygments=0.2.2=pyhd8ed1ab_0
  - jupyterlab_server=2.15.1=pyhd8ed1ab_0
  - jupyterlab_widgets=3.0.2=pyhd8ed1ab_0
  - jxrlib=1.1=h7f98852_2
  - keyutils=1.6.1=h166bdaf_0
  - kiwisolver=1.4.4=py310hbf28c38_0
  - krb5=1.19.3=h3790be6_0
  - lcms2=2.12=hddcbb42_0
  - ld_impl_linux-64=2.36.1=hea4e1c9_2
  - lerc=4.0.0=h27087fc_0
  - libaec=1.0.6=h9c3ff4c_0
  - libarchive=3.5.2=hb890918_3
  - libavif=0.10.1=h166bdaf_1
  - libblas=3.9.0=16_linux64_openblas
  - libbrotlicommon=1.0.9=h166bdaf_7
  - libbrotlidec=1.0.9=h166bdaf_7
  - libbrotlienc=1.0.9=h166bdaf_7
  - libcblas=3.9.0=16_linux64_openblas
  - libcurl=7.83.1=h7bff187_0
  - libdeflate=1.13=h166bdaf_0
  - libedit=3.1.20191231=he28a2e2_2
  - libev=4.33=h516909a_1
  - libffi=3.4.2=h7f98852_5
  - libgcc-ng=12.1.0=h8d9b700_16
  - libgfortran-ng=12.1.0=h69a702a_16
  - libgfortran5=12.1.0=hdcd56e2_16
  - libgomp=12.1.0=h8d9b700_16
  - libiconv=1.16=h516909a_0
  - liblapack=3.9.0=16_linux64_openblas
  - liblapacke=3.9.0=16_linux64_openblas
  - libllvm11=11.1.0=hf817b99_3
  - libmamba=0.25.0=hd8a31e3_2
  - libmambapy=0.25.0=py310hab0e683_2
  - libnghttp2=1.47.0=hdcd2b5c_1
  - libnsl=2.0.0=h7f98852_0
  - libopenblas=0.3.21=pthreads_h78a6416_2
  - libpng=1.6.37=h753d276_4
  - libpq=14.5=hd77ab85_0
  - libprotobuf=3.21.5=h6239696_0
  - libsodium=1.0.18=h36c2ea0_1
  - libsolv=0.7.22=h6239696_0
  - libsqlite=3.39.2=h753d276_1
  - libssh2=1.10.0=haa6b8db_3
  - libstdcxx-ng=12.1.0=ha89aaad_16
  - libtiff=4.4.0=h0e0dad5_3
  - libuuid=2.32.1=h7f98852_1000
  - libuv=1.43.0=h7f98852_0
  - libwebp-base=1.2.4=h166bdaf_0
  - libxcb=1.13=h7f98852_1004
  - libxml2=2.9.14=h22db469_4
  - libxslt=1.1.35=h8affb1d_0
  - libzlib=1.2.12=h166bdaf_2
  - libzopfli=1.0.3=h9c3ff4c_0
  - llvm-openmp=14.0.4=he0ac6c6_0
  - llvmlite=0.38.1=py310h58363a5_0
  - locket=1.0.0=pyhd8ed1ab_0
  - lxml=4.9.1=py310h5764c6d_0
  - lz4=4.0.0=py310h5d5e884_2
  - lz4-c=1.9.3=h9c3ff4c_1
  - lzo=2.10=h516909a_1000
  - mako=1.2.1=pyhd8ed1ab_0
  - mamba=0.25.0=py310hf87f941_2
  - markupsafe=2.1.1=py310h5764c6d_1
  - matplotlib-base=3.5.3=py310h8d5ebf3_2
  - matplotlib-inline=0.1.6=pyhd8ed1ab_0
  - mistune=2.0.4=pyhd8ed1ab_0
  - mpc=1.2.1=h9f54685_0
  - mpfr=4.1.0=h9202a9a_1
  - mpmath=1.2.1=pyhd8ed1ab_0
  - msgpack-python=1.0.4=py310hbf28c38_0
  - munkres=1.1.4=pyh9f0ad1d_0
  - nbclassic=0.4.3=pyhd8ed1ab_0
  - nbclient=0.6.7=pyhd8ed1ab_0
  - nbconvert=7.0.0=pyhd8ed1ab_0
  - nbconvert-core=7.0.0=pyhd8ed1ab_0
  - nbconvert-pandoc=7.0.0=pyhd8ed1ab_0
  - nbformat=5.4.0=pyhd8ed1ab_0
  - ncurses=6.3=h27087fc_1
  - nest-asyncio=1.5.5=pyhd8ed1ab_0
  - networkx=2.8.6=pyhd8ed1ab_0
  - nodejs=17.9.0=h96d913c_0
  - nomkl=1.0=h5ca1d4c_0
  - notebook=6.4.12=pyha770c72_0
  - notebook-shim=0.1.0=pyhd8ed1ab_0
  - numba=0.55.2=py310ha5257ce_0
  - numexpr=2.8.3=py310hf05e7a9_100
  - numpy=1.22.4=py310h4ef5377_0
  - oauthlib=3.2.0=pyhd8ed1ab_0
  - openblas=0.3.21=pthreads_h320a7e8_2
  - openjpeg=2.5.0=h7d73246_1
  - openssl=1.1.1q=h166bdaf_0
  - packaging=21.3=pyhd8ed1ab_0
  - pamela=1.0.0=py_0
  - pandas=1.4.3=py310h769672d_0
  - pandoc=2.19.2=ha770c72_0
  - pandocfilters=1.5.0=pyhd8ed1ab_0
  - parso=0.8.3=pyhd8ed1ab_0
  - partd=1.3.0=pyhd8ed1ab_0
  - patsy=0.5.2=pyhd8ed1ab_0
  - pexpect=4.8.0=pyh9f0ad1d_2
  - pickleshare=0.7.5=py_1003
  - pillow=9.2.0=py310hbd86126_2
  - pip=22.2.2=pyhd8ed1ab_0
  - pkgutil-resolve-name=1.3.10=pyhd8ed1ab_0
  - prometheus_client=0.14.1=pyhd8ed1ab_0
  - prompt-toolkit=3.0.30=pyha770c72_0
  - protobuf=4.21.5=py310hd8f1fbe_0
  - psutil=5.9.1=py310h5764c6d_0
  - psycopg2=2.9.3=py310h6acc77f_0
  - pthread-stubs=0.4=h36c2ea0_1001
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pure_eval=0.2.2=pyhd8ed1ab_0
  - pybind11-abi=4=hd8ed1ab_3
  - pycosat=0.6.3=py310h5764c6d_1010
  - pycparser=2.21=pyhd8ed1ab_0
  - pycurl=7.45.1=py310h2aed498_2
  - pygments=2.13.0=pyhd8ed1ab_0
  - pyjwt=2.4.0=pyhd8ed1ab_0
  - pyopenssl=22.0.0=pyhd8ed1ab_0
  - pyparsing=3.0.9=pyhd8ed1ab_0
  - pyrsistent=0.18.1=py310h5764c6d_1
  - pysocks=1.7.1=pyha2e5f31_6
  - pytables=3.7.0=py310hb60b9b2_2
  - python=3.10.6=h582c2e5_0_cpython
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python-fastjsonschema=2.16.1=pyhd8ed1ab_0
  - python-json-logger=2.0.1=pyh9f0ad1d_0
  - python_abi=3.10=2_cp310
  - pytz=2022.2.1=pyhd8ed1ab_0
  - pywavelets=1.3.0=py310hde88566_1
  - pyyaml=6.0=py310h5764c6d_4
  - pyzmq=23.2.1=py310h330234f_0
  - readline=8.1.2=h0f457ee_0
  - reproc=14.2.3=h7f98852_0
  - reproc-cpp=14.2.3=h9c3ff4c_0
  - requests=2.28.1=pyhd8ed1ab_0
  - ruamel.yaml=0.17.21=py310h5764c6d_1
  - ruamel.yaml.clib=0.2.6=py310h5764c6d_1
  - ruamel_yaml=0.15.80=py310h5764c6d_1007
  - scikit-image=0.19.3=py310h769672d_1
  - scikit-learn=1.1.2=py310h0c3af53_0
  - scipy=1.9.0=py310hdfbd76f_0
  - seaborn=0.11.2=hd8ed1ab_0
  - seaborn-base=0.11.2=pyhd8ed1ab_0
  - send2trash=1.8.0=pyhd8ed1ab_0
  - setuptools=65.3.0=pyhd8ed1ab_1
  - six=1.16.0=pyh6c4a22f_0
  - snappy=1.1.9=hbd366e4_1
  - sniffio=1.2.0=py310hff52083_3
  - sortedcontainers=2.4.0=pyhd8ed1ab_0
  - soupsieve=2.3.2.post1=pyhd8ed1ab_0
  - sqlalchemy=1.4.40=py310h5764c6d_0
  - stack_data=0.5.0=pyhd8ed1ab_0
  - statsmodels=0.13.2=py310hde88566_0
  - sympy=1.10.1=py310hff52083_1
  - tblib=1.7.0=pyhd8ed1ab_0
  - terminado=0.15.0=py310hff52083_0
  - threadpoolctl=3.1.0=pyh8a188c0_0
  - tifffile=2022.8.12=pyhd8ed1ab_0
  - tinycss2=1.1.1=pyhd8ed1ab_0
  - tk=8.6.12=h27826a3_0
  - toolz=0.12.0=pyhd8ed1ab_0
  - tornado=6.1=py310h5764c6d_3
  - tqdm=4.64.0=pyhd8ed1ab_0
  - traitlets=5.3.0=pyhd8ed1ab_0
  - typing_extensions=4.3.0=pyha770c72_0
  - tzdata=2022c=h191b570_0
  - unicodedata2=14.0.0=py310h5764c6d_1
  - urllib3=1.26.11=pyhd8ed1ab_0
  - wcwidth=0.2.5=pyh9f0ad1d_2
  - webencodings=0.5.1=py_1
  - websocket-client=1.4.0=pyhd8ed1ab_0
  - wheel=0.37.1=pyhd8ed1ab_0
  - widgetsnbextension=4.0.2=pyhd8ed1ab_0
  - xlrd=2.0.1=pyhd8ed1ab_3
  - xorg-libxau=1.0.9=h7f98852_0
  - xorg-libxdmcp=1.1.3=h7f98852_0
  - xz=5.2.6=h166bdaf_0
  - yaml=0.2.5=h7f98852_2
  - yaml-cpp=0.7.0=h27087fc_1
  - zeromq=4.3.4=h9c3ff4c_1
  - zfp=1.0.0=h27087fc_1
  - zict=2.2.0=pyhd8ed1ab_0
  - zipp=3.8.1=pyhd8ed1ab_0
  - zlib=1.2.12=h166bdaf_2
  - zlib-ng=2.0.6=h166bdaf_0
  - zstd=1.5.2=h6239696_4
  - pip:
    - psycopg2
    - sqlalchemy-utils==0.38.3
prefix: /opt/conda